// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/RomaBiliak/generate-openapi-go-server/database/dbs"
	"github.com/RomaBiliak/generate-openapi-go-server/openapi"
)

// Injectors from wire.go:

func InitializeItemApiController(db *sql.DB, opts ...openapi.ItemApiOption) openapi.Router {
	queries := dbs.New(db)
	itemApiServicer := openapi.NewItemApiService(queries)
	router := openapi.NewItemApiController(itemApiServicer, opts...)
	return router
}

func InitializeItemsApiController(db *sql.DB, opts ...openapi.ItemsApiOption) openapi.Router {
	queries := dbs.New(db)
	itemsApiServicer := openapi.NewItemsApiService(queries)
	router := openapi.NewItemsApiController(itemsApiServicer, opts...)
	return router
}
