/*
 * Test REST API
 *
 * Task №3
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"

	"github.com/RomaBiliak/generate-openapi-go-server/database/dbs"
)

// ItemsApiService is a service that implements the logic for the ItemsApiServicer
// This service should implement the business logic for every endpoint for the ItemsApi API.
// Include any external packages or services that will be required by this service.
type ItemsApiService struct {
	queries *dbs.Queries
}

// NewItemsApiService creates a default api service
func NewItemsApiService(queries *dbs.Queries) ItemsApiServicer {
	return &ItemsApiService{queries: queries}
}

// ItemsGet - All items
func (s *ItemsApiService) ItemsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ItemsGet with the required logic for this service method.
	// Add api_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Item{}) or use other options such as http.Ok ...
	//return Response(200, []Item{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ItemsGet method not implemented")
}
