/*
 * Test REST API
 *
 * Task №3
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"

	"github.com/RomaBiliak/generate-openapi-go-server/database/dbs"
)

// ItemsApiService is a service that implements the logic for the ItemsApiServicer
// This service should implement the business logic for every endpoint for the ItemsApi API.
// Include any external packages or services that will be required by this service.
type ItemsApiService struct {
	queries *dbs.Queries
}

// NewItemsApiService creates a default api service
func NewItemsApiService(queries *dbs.Queries) ItemsApiServicer {
	return &ItemsApiService{queries: queries}
}

// ItemsGet - All items
func (s *ItemsApiService) ItemsGet(ctx context.Context) (ImplResponse, error) {
	items, err:= s.queries.GetItems(ctx)

	if err != nil {
		return Response(http.StatusBadRequest, nil), err
	}

	return Response(http.StatusOK, items), nil
}
