/*
 * Test REST API
 *
 * Task №3
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateItemRequest struct {

	// Name item
	Name string `json:"name,omitempty"`

	// Value item
	Value string `json:"value,omitempty"`
}

// AssertCreateItemRequestRequired checks if the required fields are not zero-ed
func AssertCreateItemRequestRequired(obj CreateItemRequest) error {
	return nil
}

// AssertRecurseCreateItemRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateItemRequest (e.g. [][]CreateItemRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateItemRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateItemRequest, ok := obj.(CreateItemRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateItemRequestRequired(aCreateItemRequest)
	})
}
